-- ============================================================
-- Migration: 20260519110000_drop_redundant_valuation_indexes
-- Drop the single-column index on valuations(company_id) which
-- is now a strict prefix of the composite index added in
-- 20260519100000_share_prices_foundation:
--
--   idx_valuations_company_class_date
--   ON valuations(company_id, share_class_id, valuation_date desc)
--
-- PostgreSQL can use the composite index for any query that would
-- have used idx_valuations_company. Keeping the old index wastes
-- a small amount of write overhead on every INSERT / UPDATE / DELETE.
--
-- idx_valuations_date (two-column: company_id, valuation_date) is
-- intentionally kept for query-planner flexibility.
-- Decision: 19 May 2026 during review.
--
-- Not blocking — safe to apply at any time.
-- ============================================================

drop index if exists idx_valuations_company;
